### ISSUE TITLE
[Forge] Incompatibility with Performant mod.

### ISSUE THREAD

**Issue by marios-andr** [Virtuoel/Pehkui#101]
When both performant and pehkui is installed minecraft crashes. Log can be found below. Not sure if this is a problem with performant or you so I've reported the problem to both.
https://pastebin.com/hHc10ETP

MC Version: 1.16.5
Forge Version: 36.1.16
Performant: 1.16.2-3.55m
Pehkui: 1.16.5-2.0.0 (forge of course)

**Comment by Virtuoel** [comment]
Seems this occurs because Performant's `@Overwrite`ing a function to make changes and Pehkui happens to make some changes to that function as well, so the mods conflict. 
Since `@Overwrite`ing is not exactly a compatible way for them to make their changes, it would be far better for this to get fixed from their end. Good to see you've reported this to them too.
