### ISSUE TITLE
Game Won't Boot

### ISSUE THREAD

**Issue by ghost** [Virtuoel/Pehkui#104]
I am currently doing a modpack and just installed Pekhui (Forge), since I added the mod the game simply won't boot. After looking down the logs I did not see any other interaction with another mod present, the issue is present for the two latest versions of the forge version. Here is the first line of the error, hoping that it will help you quicker, there is the log file as well.
`Mixin apply failed pehkui.mixins.json:ItemEntityMixin -> net.minecraft.entity.item.ItemEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("CONSTANT") on net/minecraft/entity/item/ItemEntity::tryMergeModifyWidth with priority 1000 cannot inject into net/minecraft/entity/item/ItemEntity::func_85054_d()V merged by com.performant.coremod.mixin.entity.ItemEntityMixin with priority 1000 [PREINJECT Applicator Phase -> pehkui.mixins.json:ItemEntityMixin -> Prepare Injections ->  -> constant$zjh000$tryMergeModifyWidth(D)D -> Prepare]`
[latest.log](https://github.com/Virtuoel/Pehkui/files/6461966/latest.log)

**Comment by Virtuoel** [comment]
Not a Pehkui issue. Seems Performant's `@Overwrite`ing a function that Pehkui also makes changes to, and since `@Overwrite`ing is not a very mod-compatible way for them to make their changes it's conflicting with Pehkui's changes, causing this crash. Report to [Performant's issue tracker](https://github.com/someaddons/performant_issues/issues/) instead.

**Comment by ghost** [comment]
Thank you very much! I will consider report the issue to performant instead.
