### ISSUE TITLE
I shrank too much and now the server kicks me out instantly upon joining

### ISSUE THREAD

**Issue by CarbonatedPetrol** [Virtuoel/Pehkui#124]
I am unable to rejoin the server to reset my size due to an "internal server error" which means I will continuously be kicked out.

**Comment by Virtuoel** [comment]
If you've set yourself to an unplayable scale, theres a command-based workaround that'll reset all your scales back to their default values:
`/scale debug delete_scale_data username YourUsernameHere`

Since you're on a server, have someone that's able to use commands either run that command ingame or through the server console, then you should be able to log back into the server.
