### ISSUE TITLE
Gravity

### ISSUE THREAD

**Issue by LoganDark** [Virtuoel/Pehkui#20]
Pehkui is just a size mod right now, but what about changing entity gravity? For example, standing on a wall or ceiling.. just an interesting idea

**Comment by ImSpaceLover** [comment]
It really is. But isn't it worth creating a separate mod for this function?

**Comment by LoganDark** [comment]
@ImSpaceLover The mod developer already said that they'd be interested in increasing the scope of pehkui like this, there was a discussion on fabricord about it

**Comment by Virtuoel** [comment]
Interested in creating something for modifying the gravity vector of an entity, yes, but whether I would have that be part of Pehkui or another mod is still to be determined.

**Comment by LoganDark** [comment]
Heck, guess I misunderstood then...

**Comment by muzikbike** [comment]
So like the old mineup/gravitycraft mod for 1.2.5, and that one gravity mod for 1.12.2?

**Comment by ImSpaceLover** [comment]
I think this "issue" must be closed, when someone opened an issue asking for RGB/HEX skin-changing, you closed it saying that this is out of the mod's scope. Gravity changing is out of scope too. If you really want to make a gravity mod, you can help this guy `Fusion Flux#9885` who is currently looking for devs who can help with their GravityLib (he wrote a message about it in requests on The Fabric Project server) but otherwise, I don't see why this issue could still be opened.
