### ISSUE TITLE
Unable to get base scale and motion scale to stay after death

### ISSUE THREAD

**Issue by BubbleStretch** [Virtuoel/Pehkui#271]
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

36.2.33

### In what environment did the problem occur?

A multiplayer server that I was connected to

### What went wrong? (Crash logs don't go here)

so, me and a buddy are playing on his aternos server, we've adjusted the settings to keep scales after death, we set everything to persist but, when we die our base scale and our motion scale are just reset, is there any way we messed something up?

### Full list of installed mods

![image](https://user-images.githubusercontent.com/86279429/167013431-b048a22b-c8bc-4937-9e71-87ecc7e72af9.png)

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
This appears to be caused by CustomPlayerModels [setting scales when respawning](https://github.com/tom5454/CustomPlayerModels/blob/master/CustomPlayerModels/src/shared/java/com/tom/cpm/shared/network/NetHandler.java#L241-L249) without first checking e.g. if the scale is persistent. If this still happens with the latest vesion of CustomPlayerModels, create an issue on [their issue tracker](https://github.com/tom5454/CustomPlayerModels/issues) instead.
