### ISSUE TITLE
Crafting table bug

### ISSUE THREAD

**Issue by TonyTorzido** [Virtuoel/Pehkui#293]
I am using Valhelsia Vanilla Expanded 1.18.2 with origins mod. Everything was going well until I installed this mod for fabric 1.18.2 along with origins++ 1.18.2. I installed different version of Pehkui and the crafting table issue continued until I uninstalled. 

I can still click the box and get the items, but I can't see them. Any tips?

![image](https://user-images.githubusercontent.com/74726119/176563552-c4fe5e1e-e2fb-41d3-aff5-f7a4660ce850.png)

**Comment by Virtuoel** [comment]
Pehkui does not change anything to do with crafting, so I don't know what would be causing this.

Does this still happen with Pehkui _and_ without Origins++?
If this only happens when _both_ Pehkui and Origins++ are present, report to [Origins++](https://github.com/QuantumXenon/origins-plus-plus/issues) instead.

**Comment by Virtuoel** [comment]
Looking at your issue on Origins++, this was caused by fastbench. Glad you figured it out.
