### ISSUE TITLE
[Bug]: the /scale command doesnt work using command blocks

### ISSUE THREAD

**Issue by qua6ky** [Virtuoel/Pehkui#294]
### Minecraft version(s)

1.19.1

### Mod loader

Forge

### Mod loader version

1.19

### In what environment did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

I put the command /scale set 0.3 @a and it doesnt scale new players

### Full list of installed mods

Only pehkui 

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
When you say "new players", it makes it sound like you're expecting future players to be rescaled too. `@a` can only target players who are logged in. For scaling new players as well, I'd recommend using the command in a repeating command block, maybe with a filter too.

If that is not what you mean, please give more info about the problem and I'll reopen the issue if the problem is something that's broken on Pehkui's end.
