### ISSUE TITLE
Pehkui Breaks when I use a command block on a server.

### ISSUE THREAD

**Issue by Ax0l0tlz** [Virtuoel/Pehkui#308]
### Minecraft version(s)

1.18.2, 1.19.1

### Mod loader

Fabric

### Mod loader version

14.9

### Fabric API version

0.57.0

### In what environment did the problem occur?

A multiplayer server that I was connected to

### What went wrong? (Crash logs don't go here)

I could set my scale as normal but when I tried to make it permanent with a repeating command block the entirety of pehkui broke and no commands command block or not would work if it was pehkui related.

### Full list of installed mods

Sodium,Fabric API, Pehkui.

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
Unable to reproduce. Closest thing I could get was having a repeating command block setting a scale which prevented changing that scale until the command block is disabled.

If you want to prevent a scale from resetting after death, it's better to use `/scale persist set <type> true` instead of constantly setting the scale.

If persisting after death is not enough and you still have the problem, please explain, and also provide the commands you ran (a video would be useful too) in another comment here so I can better understand what steps you did and what problems occur, then I will reopen the issue if it looks like something's acting strangely.
