### ISSUE TITLE
[Suggestion]: Bridge between Better Combat and Pehkui

### ISSUE THREAD

**Issue by bassistracer** [Virtuoel/Pehkui#314]
### What is your suggestion?

Hey, big fan of Pehkui! I was hoping I could reach out and maybe have some help bridging it between that and a new Fabric mod on the block called [Better Combat.](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)

Essentially, the mod maker of Better Combat wants to add Pehkui support -- but DOESN'T want to add a gradle dependency on it. He hasn't exactly been able to find any contact info nor anything on the Minecraft Vanilla API in the documents, so, figured I could probably just open an issue here.
[Here's the issue I opened on the BC mod for a bit more info.](https://github.com/ZsoltMolnarrr/BetterCombat/issues/49)
Thanks for reading.

**Comment by Virtuoel** [comment]
As they mentioned using attributes, instead of using Pehkui directly it would probably be better if they were to make use of [Reach-Entity-Attributes](https://github.com/JamiesWhiteShirt/reach-entity-attributes/), which Pehkui has compat code for to adjust the attribute values based on one's scale. Would also improve compat with other mods that use and affect attack and block reach.

**Comment by Virtuoel** [comment]
Resolved on Better Combat's end.
