### ISSUE TITLE
[Bug]: Ride position is not accurate in small scale when I ride vehicles added by mod.

### ISSUE THREAD

**Issue by DGKaru** [Virtuoel/Pehkui#339]
### Minecraft version(s)

1.19.2

### Mod loader

Forge

### Mod loader version

43.1.33

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

[Bug]: Ride position is not accurate in small scale when I ride vehicles added by mod. (like this video)

https://user-images.githubusercontent.com/89735034/200290265-650e2e19-73bb-40a6-85de-8f94933ec026.mp4

### Full list of installed mods and their version numbers

BetterThirdPerson-Forge-1.19-1.8.1
OptiFine_1.19.2_HD_U_H9
Pehkui-3.6.0+1.19.2-forge
simpleplanes-1.19.2-5.0.3
worldedit-mod-7.2.12

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by DistantDig** [comment]
This also occurs in fabric with any mount, including vanilla's horses. Its mostly problematic for smaller races when playing with the Origins mod, since smaller players will float over the entity they are riding

**Comment by Virtuoel** [comment]
Fixed for vanilla entities as of 3.7.8 release.

For the plane mod, they apparently have some of their vehicles' passenger offsets hardcoded.
e.g. the small plane currently uses `0.5` instead of a value like `getHeight() / 3.6` or something like that, which would work when that plane is at any scaled size.
Would be best to report that to them instead.
