### ISSUE TITLE
[Bug]: Scale persist true not working

### ISSUE THREAD

**Issue by Karpainen** [Virtuoel/Pehkui#355]
### Minecraft version(s)

1.19.2

### Mod loader

Forge

### Mod loader version

Forge 43.1.7

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

"scale persist set true" command is not working. When my character dies and respawns, all my scale settings are reset. Example: If I type command "/scale set pehkui:base 3 MyName" and then I will respawn, I am back in basic size.

### Full list of installed mods and their version numbers

BadMobs-1.19.2-16.1.3
Custom PlayerModels-1.19-0.6.2a
DramaticDoors-Forge-1.19.2-2.1.6
dynamiclights-1.19.2.1
FallingTree-1.19.2-3.10.0
firstperson-forge-2.2.0-mc1.19.2
jei-1.19.2-forge-11.5.0.297
Kiwi-1.19.1-forge-8.1.3
moveplus-1.19.2-2.5.1
notenoughanimations-forge-1.6.2-mc1.19.2
oculus-mc1.19.2-1.2.8
PassableFoliage-1.19.1-forge-5.0.1
Pehkui-3.6.1+1.19.2-forge
rubidium-0.6.2
soundphysics-forge-1.19.2-1.0.18
Female-Gender-Mod-forge-1.19.1-3.0.1

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Karpainen** [comment]
Haloo?!

**Comment by Virtuoel** [comment]
This appears to be caused by CustomPlayerModels [setting scales when respawning](https://github.com/tom5454/CustomPlayerModels/blob/master/CustomPlayerModels/src/shared/java/com/tom/cpm/shared/network/NetHandler.java#L241-L249) without first checking e.g. if the scale is persistent. If this still happens with the latest vesion of CustomPlayerModels, create an issue on [their issue tracker](https://github.com/tom5454/CustomPlayerModels/issues) instead.
