### ISSUE TITLE
[Bug][1.19.2 - Fabric - v3.6.3+1.14.4] Server Watchdog Crash - Accessing Entity with no Scale Data?

### ISSUE THREAD

**Issue by Elfinlocks** [Virtuoel/Pehkui#377]
### Minecraft version(s)

1.19.2

### Mod loader

Fabric

### Mod loader version

0.14.14

### Fabric API version

0.73.2

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

Getting a watchdog crash on a multiplayer server when loading in. It seems that the mod is trying to access scale data for an entity that doesn't exist, which is causing the server to crash.

### Full list of installed mods and their version numbers

Modlist link: https://www.curseforge.com/minecraft/modpacks/elven-fabric-aof6-smp-edit/files/4405526

Modlist too long to paste, see crashlog

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

Too long - hastebin link: https://hastebin.com/share/sudokijoke.php

**Comment by Virtuoel** [comment]
When the Watchdog kills a server, it's typically due to some sort of lag, just that it happened to stop the server at the same time as Pehkui was doing stuff. Looking at your crash log, it appears that your server had 9267 item entities loaded at the time of the crash. Maybe a Create contraption gone wrong making too many items?
