### ISSUE TITLE
[Bug]: Incompatibility with Probably Chests causing pet mimics to be unresponsive

### ISSUE THREAD

**Issue by ArcanePigeon** [Virtuoel/Pehkui#395]
### Minecraft version(s)

1.19.2

### Mod loader

Quilt

### Mod loader version

Quilt 0.18.6

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

I am the developer of Probably Chests and it was brought to my attention that with pehkui installed that new pet mimics become unresponsive. https://github.com/ArcanePigeon/ProbablyChests/issues/52 This is a link to the report sent to me and I have not had the time to get around to working on the mods recently and wanted to check in with you and see if you already know what could be causing the issue.

### Full list of installed mods and their version numbers

Probably Chests 0.5.5
GeckoLib 3.1.41
Cloth Config API 8.2.88
Pehkui 3.7.2
Quilted Fabric API 4.0.0 beta.30 + Quilt Standard Libraries 3.0.0 beta.29 for Fabric API 0.76.0

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by BlueAgent** [comment]
Hello, after looking into this it turned out that the entity did not have an updated bounding box on the server, which Pehkui uses for [checking interaction distance limit instead of the entity position](https://github.com/Virtuoel/Pehkui/blob/d4c49cadcb9bc857b1ea9540e1a3ce3592098886/src/main/java/virtuoel/pehkui/mixin/compat119plus/compat1193minus/ServerPlayNetworkHandlerMixin.java#L21-L79).

Bounding Box not updated should be fixed with https://github.com/ArcanePigeon/ProbablyChests/pull/53.

I think if there was a change to make for Pehkui it could be some of these options:

1. Using the minimum of the current eye to nearest bounding box and the existing eye to entity position.
2. Updating the entity's bounding box if the position is not contained within the bounding box.
3. A warning if the pehkui distance calculation is less than the original one (kind of an alternative to 1).

I'm not sure I like any of these options as I think the bounding box of an entity doesn't necessarily have to contain the position as well (the warning might not totally make sense should a bounding box be above the position and you interact from below it). And it would also hide issues with the bounding box not updating and make it harder to identify that is the case. It also doesn't address out of sync bounding boxes not having proper collision... So perhaps no change is better here.

**Comment by Virtuoel** [comment]
I also agree that no change on Pehkui's end would be better here.
Closing now that the https://github.com/ArcanePigeon/ProbablyChests/pull/53 PR was created.
