### ISSUE TITLE
[Bug]: Scale Persist not working

### ISSUE THREAD

**Issue by artyrabbit** [Virtuoel/Pehkui#405]
### Minecraft version(s)

1.19.2

### Mod loader

Fabric

### Mod loader version

fabric

### Fabric API version

0.76.0

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

When I do /scale persist set true it doesnt work. I've tried it both on singleplayer and multiplayer but it does not work.

### Full list of installed mods and their version numbers

[Argonauts Official Modpack.zip](https://github.com/Virtuoel/Pehkui/files/11361977/Argonauts.Official.Modpack.zip)

### Did the problem cause the game to crash?

No.

**Comment by ImStrikeTV** [comment]
Boost-- having the same issue.

**Comment by Virtuoel** [comment]
This appears to be caused by CustomPlayerModels [setting scales when respawning](https://github.com/tom5454/CustomPlayerModels/blob/master/CustomPlayerModels/src/shared/java/com/tom/cpm/shared/network/NetHandler.java#L241-L249) without first checking e.g. if the scale is persistent. If this still happens with the latest vesion of CustomPlayerModels, create an issue on [their issue tracker](https://github.com/tom5454/CustomPlayerModels/issues) instead.
