### ISSUE TITLE
How to resize any spesifik entities from other mods

### ISSUE THREAD

**Issue by GezaRamadhani01** [Virtuoel/Pehkui#412]
Hello, I am using other mod like Untamed Wilds, and I want to resize entities like anaconda more big size, how I know code from entities ?

**Comment by Aceplante** [comment]
it should be approximately something to the effect of /scale set @e[type=untamedwilds:anaconda] base 2

Of course, replace untamedwilds with whatever the mod namespace actually is, and also I am not able to completely verify the format because I do not have admin permissions on the world I am currently on, but it should be similar to what I put above

**Comment by Virtuoel** [comment]
Above example was pretty close. The format would be as follows:
`/scale set pehkui:base 2 @e[type=mod_id:entity_type]`

Using the F3 screen, the entity type should be visible on the right of the screen when looking at the entity.
