### ISSUE TITLE
[Bug]: Registry remapping failed?

### ISSUE THREAD

**Issue by LittleJay69** [Virtuoel/Pehkui#421]
### Minecraft version(s)

Other (specify below)

### Minecraft version details

1.19

### Mod loader

Fabric

### Mod loader version

(Not sure just 1.19 fabric???)

### In what kind of world or server did the problem occur?

A multiplayer server that I was connected to

### What went wrong? (Crash logs don't go here)

![image_2023-06-17_171434513](https://github.com/Virtuoel/Pehkui/assets/136935226/c0706d58-b47a-4c02-9a4c-f4c09b17f775)

I keep getting this error id/code that wont let me play, i restarted my laptop, Uninstalled, reinstalled, made sure its the right verison, and still wont work. I was using 1.19 for origins and this image popped up everytime i tried joining the server.

### Full list of installed mods and their version numbers

![image](https://github.com/Virtuoel/Pehkui/assets/136935226/e973d905-7fbd-479c-95b0-277cc03090ed)
Each mod on 1.19 including the barely visible ones at the bottom

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
Seeing that error usually means the Pehkui version you have on your client is outdated.
Alternatively, since you said you're on just 1.19, the Fabric API you have on your client may also be outdated.

Make sure the mods on your client are the same version numbers as the mods on your server. Since your screenshot has no version numbers, I can't really verify which ones you're using.
