### ISSUE TITLE
[Bug]: 2+ tall blocks players can`t connect to server

### ISSUE THREAD

**Issue by MrHugger** [Virtuoel/Pehkui#447]
### Minecraft version(s)

1.20.1

### Mod loader

Fabric

### Mod loader version

0.14.21

### Fabric API version

fabric-api-0.85.0+1.20.1

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

Using mod origins + datapacs for races. Some races abilities include increasing size of a player, example will be in crash report content. When a player on a server choses a race with 2+ blocks tall, he can play normally (including reconnects) until rebooting the server. After the server reboots, when a player tries to connect there is an error "Invalid player data". After removing ability for height player can connect normally.

### Full list of installed mods and their version numbers

[list of mods from log.txt](https://github.com/Virtuoel/Pehkui/files/12405950/list.of.mods.from.log.txt)

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

Ability for changing height:
[threeblockstall.txt](https://github.com/Virtuoel/Pehkui/files/12405919/threeblockstall.txt)
What happens in server log:
[server log.txt](https://github.com/Virtuoel/Pehkui/files/12405941/server.log.txt)

**Comment by Virtuoel** [comment]
Looks to be a conflict between that origin power and EasyAuth, where the origin tries to run a command when the power is added, including when the player gets loaded from its NBT, which happens before they're auth'd by EasyAuth. EasyAuth then tries to send the player an error message via chat, but can't since they're so early in the loading there's no network connection yet.
Not a Pehkui issue, report to EasyAuth.

**Comment by MrHugger** [comment]
Thanks for pretty fast response
