### ISSUE TITLE
Pehkui causes a crash upon opening a world.

### ISSUE THREAD

**Issue by Mysteriaa** [Virtuoel/Pehkui#46]
[crash-2021-03-09_13.20.51-client.txt](https://github.com/Virtuoel/Pehkui/files/6110703/crash-2021-03-09_13.20.51-client.txt)
Found this with Just Enough Crashes. It seems to be having trouble registering commands.

**Comment by CmdrJane** [comment]
its also crashes with terrestria, simply platinum, carrier and almost with every other mods that i have installed

**Comment by tyra314** [comment]
After an update of my personal odpack I noticed that issue as well. Turns out, it crashes, when Bewitchment-1.16.5-5 is loaded. With the older Bewitchment-1.16.5-4, it works fine. It seems quite odd, as Bewitchment is the reason I have Pehkui in that pack. But it is what it is.

I also have Terrestria and that is definitly not the culprit.

**Comment by tyra314** [comment]
I went on a bug hunt. The longer version is in the [Bewitchment issue here](https://github.com/MoriyaShiine/bewitchment/issues/57#issuecomment-796308011).

The short version is. Due to the undefined mod initialization order, Bewitchment might load classes of Pekhui before [this code](https://github.com/Virtuoel/Pehkui/blob/1.17/src/main/java/virtuoel/pehkui/Pehkui.java#L35) has a chance to run. This messes up the ScaleRegistries, which end up with `null` as key for some entries.
